name: Build app
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Setup ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21d
      - name: Build the app
        run: |
          ndk-build NDK_PROJECT_PATH=app/src/main NDK_LIBS_OUT=app/src/main/jniLibs
          ./gradlew assembleRelease
        working-directory: ./app
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        id: sign_app
        with:
          releaseDirectory: app/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Signed app
          path: ${{steps.sign_app.outputs.signedReleaseFile}}